services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.0
    container_name: elasticsearch
    networks:
      - baekgwa-network
    ports:
      - ${ELASTIC_SEARCH_PORT}:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./elastic/init-kibana-user.sh:/usr/share/elasticsearch/config/init/init-kibana-user.sh
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - KIBANA_USERNAME=${KIBANA_USERNAME} # Kibana -> Elastic 접속을 위한 회원 아이디, 기존 elastic system 계정을 사용하는 방법은 막힘
      - KIBANA_PASSWORD=${KIBANA_PASSWORD} # Kibana -> Elastic 접속을 위한 회원 비밀번호
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "bash /usr/share/elasticsearch/config/init/init-kibana-user.sh && /usr/local/bin/docker-entrypoint.sh"
      ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -f -u elastic:${ELASTICSEARCH_PASSWORD} http://localhost:9200/_cluster/health" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.0
    container_name: kibana
    networks:
      - baekgwa-network
    ports:
      - ${KIBANA_PORT}:5601
    volumes:
      - kibana-data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      # Kibana -> Elastic 으로 접속할 떄 사용할 유저는, "kibana_system" 권한을 가지고 있는 새로 만든 유저
      - ELASTICSEARCH_USERNAME=${KIBANA_USERNAME}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - SERVER_PUBLICBASEURL=https://kibana.baekgwa.site
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${KIBANA_ENCRYPTED_SAVED_OBJECTS_ENCRYPTION_KEY}
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy

  logstash:
    image: docker.elastic.co/logstash/logstash:9.2.0
    container_name: logstash
    networks:
      - baekgwa-network
    ports:
      - ${LOGSTASH_PORT}:5044
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      - LS_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy

  elastic-agent:
    image: docker.elastic.co/elastic-agent/elastic-agent:9.2.3
    container_name: elastic-agent
    networks:
      - baekgwa-network
    ports:
      - ${FLEET_SERVER_PORT}:8220
      - ${ELASTIC_APM_PORT}:8200
    environment:
      - FLEET_SERVER_ENABLE=true
      - FLEET_SERVER_ELASTICSEARCH_HOST=http://elasticsearch:9200
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - FLEET_SERVER_POLICY_ID=fleet-server-policy
      - FLEET_URL=http://elastic-agent:8220 #내부 agent 들이 fleet 서버를 바라볼 주소. 현재 fleet server를 elastic-agent container 하나로 관리하기 때문에, 본인 스스로 지칭
      - FLEET_SERVER_INSECURE_HTTP=true
      - FLEET_SERVER_SERVICE_TOKEN=${FLEET_SERVER_SERVICE_TOKEN}
      - FLEET_ENROLLMENT_TOKEN=${FLEET_ENROLLMENT_TOKEN}
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_started
    restart: always

volumes:
  es-data:
    driver: local
  kibana-data:
    driver: local

networks:
  baekgwa-network:
    external: true